services:
  # API Product Service
  api_product:
    build: ./api_product/
    container_name: product_service
    ports:
      - "3001:3000" 
    depends_on:
      mysql_product:
        condition: service_healthy
    env_file:
      - ./api_product/.env
    environment:
      - JWT_SECRET=my_secret_tokect_key
    restart: always

  # MySQL Database for Product Service
  mysql_product:
    image: mysql:8
    container_name: product_db
    environment:
      MYSQL_ROOT_PASSWORD: Root_Password123!
      MYSQL_DATABASE: mydb_product
      MYSQL_USER: product_user
      MYSQL_PASSWORD: product_pass 
    volumes:
      - product_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRoot_Password123!"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # API Client Service
  api_client:
    build: ./api_client/
    container_name: client_service
    ports:
      - "3002:3000" 
    depends_on:
      mysql_client:
        condition: service_healthy
    env_file:
      - ./api_client/.env
    restart: always

  # MySQL Database for Client Service
  mysql_client:
    image: mysql:8
    container_name: client_db
    environment:
      MYSQL_ROOT_PASSWORD: Root_Password123!
      MYSQL_DATABASE: mydb_client
      MYSQL_USER: client_user
      MYSQL_PASSWORD: client_pass
    volumes:
      - client_db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pRoot_Password123!"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  # API Commands Service
  api_commands:
    build: ./api_command/
    container_name: commands_service
    ports:
      - "3003:3000" 
    depends_on:
      mongodb_commands:
        condition: service_healthy
    env_file:
      - ./api_command/.env
    restart: always

  # MongoDB Database for Commands Service
  mongodb_commands:
    image: mongo:latest
    container_name: commands_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password123
      MONGO_INITDB_DATABASE: mydb_commands
    volumes:
      - commands_db_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always


  # API Gateway 
  gateway:
      image: nginx:stable-alpine
      container_name: api_gateway
      ports:
        - "80:80"
      volumes:
        - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - api_product
        - api_client
        - api_commands
      restart: always
  
  # Api Authentication Service
  api_auth:
    build: ./api_auth
    container_name: auth_service
    ports:
      - "3004:3000"
    environment:
      - DB_HOST=auth_db
      - JWT_SECRET=my_secret_tokect_key
    depends_on:
      auth_db:
        condition: service_healthy 
    restart: always

  # MySQL Database for Authentication Service
  # MySQL Database for Auth Service
  auth_db:
    image: mysql:8
    container_name: auth_db
    environment:
      MYSQL_ROOT_PASSWORD: Root_Password123!
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_pass
    volumes:
      - auth_db_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pRoot_Password123!",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5



volumes:
  product_db_data:
  commands_db_data:
  client_db_data:
  auth_db_data:
  rabbitmq_data: