server {
    listen 80;
    resolver 127.0.0.11 valid=30s;

    error_page 401 = @error_401;
    error_page 403 = @error_403;
    error_page 502 503 504 = @json_error;


    location = /auth-verify {
        internal;
        set $upstream_auth api_auth;
        
        proxy_pass http://$upstream_auth:3000/api/auth/verify;
        
        proxy_pass_request_body off;
        proxy_set_header Content-Length "";
        proxy_set_header X-Original-URI $request_uri;
    }


    location /api/products {
        auth_request /auth-verify; # protecttion
        set $upstream_product api_product;
        proxy_pass http://$upstream_product:3000;
        proxy_intercept_errors on;
    }

    location /api/clients {
        auth_request /auth-verify; 
        set $upstream_client api_client;
        proxy_pass http://$upstream_client:3000;
        proxy_intercept_errors on;
    }

    location /api/commands {
        auth_request /auth-verify; 
        set $upstream_commands api_commands;
        proxy_pass http://$upstream_commands:3000;
        proxy_intercept_errors on;
    }

   
    location /api/auth {
        set $upstream_auth api_auth;
        proxy_pass http://$upstream_auth:3000;
        proxy_intercept_errors on;
    }

    location @json_error {
        default_type application/json;
        return 502 '{"status": 502, "message": "Service is temporarily unavailable.", "service": "Backend Gateway"}';
    }

    location @error_403 {
        default_type application/json;
        return 403 '{"status": 403, "message": "Forbidden. Your token is invalid or expired."}';
    }


    location @error_401 {
        default_type application/json;
        return 401 '{"status": 401, "message": "Unauthorized. You must provide a valid token."}';
    }
}

