server {
    listen 80;

   
    resolver 127.0.0.11 valid=30s;

    error_page 502 503 504 = @json_error;

    location /api/products {
        set $upstream_product api_product;
        proxy_pass http://$upstream_product:3000;
        proxy_intercept_errors on;
    }

    location /api/clients {
        set $upstream_client api_client;
        proxy_pass http://$upstream_client:3000;
        proxy_intercept_errors on;
    }

    location /api/commands {
        set $upstream_commands api_commands;
        proxy_pass http://$upstream_commands:3000;
        proxy_intercept_errors on;
    }

    location @json_error {
        default_type application/json;
        return 502 '{"status": 502, "message": "Service is temporarily unavailable.", "service": "Backend Gateway"}';
    }
}


# server {
#     listen 80;

#     error_page 502 503 504 = @json_error;    


#     location /api/products {
#         proxy_pass http://api_product:3000;
#         proxy_intercept_errors on;
#     }

    
#     location /api/clients {
#         proxy_pass http://api_client:3000;
#         proxy_intercept_errors on;
#     }

    
#     location /api/commands {
#         proxy_pass http://api_commands:3000;
#         proxy_intercept_errors on;
#     }


#     location @json_error {
#         default_type application/json;
#         return 502 '{"status": 502, "message": "Service is temporarily unavailable. Please try again later.", "service": "Backend Gateway"}';
#     }
# }