server {
    listen 80;

    
    location /api/products {
        proxy_pass http://api_product:3000;
    }

    
    location /api/clients {
        proxy_pass http://api_client:3000;
    }

    
    location /api/commands {
        proxy_pass http://api_commands:3000;
    }
}